//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.03 at 04:19:27 PM CEST
//
package org.modelio.module.attacktreedesigner.conversion.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for operatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operatorType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;choice maxOccurs="unbounded" minOccurs="2">
 * &lt;element name="attack" type="{}attackType"/>
 * &lt;element name="treeReference" type="{}treeReferenceType"/>
 * &lt;/choice>
 * &lt;/sequence>
 * &lt;attribute name="type" use="required" type="{}operationType" />
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("2b14c7fe-8579-4c5c-9403-38e714f431a5")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operatorType", propOrder = {
    "attackOrTreeReference"
})
public class OperatorType {
    @objid ("e2239f72-b912-4b3a-b3a9-5e88570f6319")
    @XmlAttribute(name = "type", required = true)
    protected OperationType type;

    @objid ("16619ce3-6a6c-4179-bea2-ef43584cfe93")
    @XmlElements({
        @XmlElement(name = "attack", type = AttackType.class),
        @XmlElement(name = "treeReference", type = TreeReferenceType.class)
    })
    protected List<Object> attackOrTreeReference;

    /**
     * Gets the value of the attackOrTreeReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attackOrTreeReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     * getAttackOrTreeReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttackType }
     * {@link TreeReferenceType }
     */
    @objid ("95a54f62-0b32-47ac-8455-b6d1735091bb")
    public List<Object> getAttackOrTreeReference() {
        if (attackOrTreeReference == null) {
            attackOrTreeReference = new ArrayList<Object>();
        }
        return this.attackOrTreeReference;
    }

    /**
     * Gets the value of the type property.
     * @return
     * possible object is
     * {@link OperationType }
     */
    @objid ("70c55617-483a-4af8-a920-3d360c7acd5a")
    public OperationType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * @param value allowed object is
     * {@link OperationType }
     */
    @objid ("05cc626a-3a1f-4ff1-8d11-f5a870568db3")
    public void setType(OperationType value) {
        this.type = value;
    }

}
