//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.10.04 at 05:00:25 PM CEST
//
package org.modelio.module.attacktreedesigner.conversion.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.modeliosoft.modelio.javadesigner.annotations.objid;

/**
 * <p>Java class for attackTreeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="attackTreeType">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;sequence>
 * &lt;element name="treeDiagram" type="{}treeDiagramType"/>
 * &lt;element name="attack" type="{}attackType"/>
 * &lt;/sequence>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@objid ("d6a4414d-15c5-435e-80f9-221d3be6e05e")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "attackTreeType", propOrder = {
    "treeDiagram",
    "attack"
})
@XmlRootElement(name="attackTree")
public class AttackTreeType {
    @objid ("861787b8-ca29-4925-ba18-09c0cdf67157")
    @XmlElement(required = true)
    protected TreeDiagramType treeDiagram;

    @objid ("eee15e5c-7f37-4516-be63-ffaab39aeee3")
    @XmlElement(required = true)
    protected AttackType attack;

    /**
     * Gets the value of the treeDiagram property.
     * @return
     * possible object is
     * {@link TreeDiagramType }
     */
    @objid ("0d227bee-e6a7-4101-99c9-d17f21cfb573")
    public TreeDiagramType getTreeDiagram() {
        return this.treeDiagram;
    }

    /**
     * Sets the value of the treeDiagram property.
     * @param value allowed object is
     * {@link TreeDiagramType }
     */
    @objid ("46af9018-0e23-4394-ace7-a8a64f172457")
    public void setTreeDiagram(TreeDiagramType value) {
        this.treeDiagram = value;
    }

    /**
     * Gets the value of the attack property.
     * @return
     * possible object is
     * {@link AttackType }
     */
    @objid ("4741ce44-f0ca-4212-9a01-a4cee39a72b4")
    public AttackType getAttack() {
        return this.attack;
    }

    /**
     * Sets the value of the attack property.
     * @param value allowed object is
     * {@link AttackType }
     */
    @objid ("e59d963a-27b3-461b-966c-0716da38e24c")
    public void setAttack(AttackType value) {
        this.attack = value;
    }

}
